version: "3"

services:
    web:
        build: .
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        networks:
            - network
        command: ["./wait-for-it.sh", "database:3306", "--", "python", "app.py"]
    database:
        image: mariadb:10.3.32
        environment:
            MYSQL_DATABASE: gs2_insight
            MYSQL_USER: app
            MYSQL_PASSWORD: app
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        networks:
            - network

networks:
    network:
        external: true
