version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.4.0

executors:
  python_default:
    docker:
      - image: cimg/python:3.7
    resource_class: medium

jobs:
  deploy_ap_northeast_1_dev:
    executor: python_default
    environment:
      AWS_REGION: ap-northeast-1
      AWS_ECR_REGISTRY_ID: "193652665524"
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: gs2-insight
          setup-remote-docker: true
          tag: latest

  deploy_us_east_1_dev:
    executor: python_default
    environment:
      AWS_REGION: us-east-1
      AWS_ECR_REGISTRY_ID: "193652665524"
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: gs2-insight
          setup-remote-docker: true
          tag: latest

  deploy_eu_west_1_dev:
    executor: python_default
    environment:
      AWS_REGION: eu-west-1
      AWS_ECR_REGISTRY_ID: "193652665524"
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: gs2-insight
          setup-remote-docker: true
          tag: latest

  deploy_ap_southeast_1_dev:
    executor: python_default
    environment:
      AWS_REGION: ap-southeast-1
      AWS_ECR_REGISTRY_ID: "193652665524"
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: gs2-insight
          setup-remote-docker: true
          tag: latest

  deploy_ap_northeast_2_dev:
    executor: python_default
    environment:
      AWS_REGION: ap-northeast-2
      AWS_ECR_REGISTRY_ID: "193652665524"
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: gs2-insight
          setup-remote-docker: true
          tag: latest

  deploy_ap_south_1_dev:
    executor: python_default
    environment:
      AWS_REGION: ap-south-1
      AWS_ECR_REGISTRY_ID: "193652665524"
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: gs2-insight
          setup-remote-docker: true
          tag: latest

  deploy_us_west_2_dev:
    executor: python_default
    environment:
      AWS_REGION: us-west-2
      AWS_ECR_REGISTRY_ID: "193652665524"
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: gs2-insight
          setup-remote-docker: true
          tag: latest

  deploy_eu_central_1_dev:
    executor: python_default
    environment:
      AWS_REGION: eu-central-1
      AWS_ECR_REGISTRY_ID: "193652665524"
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: gs2-insight
          setup-remote-docker: true
          tag: latest

  deploy_ap_northeast_1_live:
    executor: python_default
    environment:
      AWS_REGION: ap-northeast-1
      AWS_ECR_REGISTRY_ID: "258965805804"
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: gs2-insight
          setup-remote-docker: true
          tag: latest

  deploy_us_east_1_live:
    executor: python_default
    environment:
      AWS_REGION: us-east-1
      AWS_ECR_REGISTRY_ID: "258965805804"
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: gs2-insight
          setup-remote-docker: true
          tag: latest

  deploy_eu_west_1_live:
    executor: python_default
    environment:
      AWS_REGION: eu-west-1
      AWS_ECR_REGISTRY_ID: "258965805804"
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: gs2-insight
          setup-remote-docker: true
          tag: latest

  deploy_ap_southeast_1_live:
    executor: python_default
    environment:
      AWS_REGION: ap-southeast-1
      AWS_ECR_REGISTRY_ID: "258965805804"
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: gs2-insight
          setup-remote-docker: true
          tag: latest

  deploy_ap_northeast_2_live:
    executor: python_default
    environment:
      AWS_REGION: ap-northeast-2
      AWS_ECR_REGISTRY_ID: "258965805804"
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: gs2-insight
          setup-remote-docker: true
          tag: latest

  deploy_ap_south_1_live:
    executor: python_default
    environment:
      AWS_REGION: ap-south-1
      AWS_ECR_REGISTRY_ID: "258965805804"
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: gs2-insight
          setup-remote-docker: true
          tag: latest

  deploy_us_west_2_live:
    executor: python_default
    environment:
      AWS_REGION: us-west-2
      AWS_ECR_REGISTRY_ID: "258965805804"
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: gs2-insight
          setup-remote-docker: true
          tag: latest

  deploy_eu_central_1_live:
    executor: python_default
    environment:
      AWS_REGION: eu-central-1
      AWS_ECR_REGISTRY_ID: "258965805804"
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: gs2-insight
          setup-remote-docker: true
          tag: latest

workflows:
  build-and-deploy:
    jobs:
      - deploy_ap_northeast_1_dev:
          context: EcrPushDev
          filters:
            branches:
              only:
                - main
      - deploy_us_east_1_dev:
          context: EcrPushDev
          filters:
            branches:
              only:
                - main
      - deploy_eu_west_1_dev:
          context: EcrPushDev
          filters:
            branches:
              only:
                - main
      - deploy_ap_southeast_1_dev:
          context: EcrPushDev
          filters:
            branches:
              only:
                - main
      - deploy_ap_northeast_2_dev:
          context: EcrPushDev
          filters:
            branches:
              only:
                - main
      - deploy_ap_south_1_dev:
          context: EcrPushDev
          filters:
            branches:
              only:
                - main
      - deploy_us_west_2_dev:
          context: EcrPushDev
          filters:
            branches:
              only:
                - main
      - deploy_eu_central_1_dev:
          context: EcrPushDev
          filters:
            branches:
              only:
                - main

      - deploy_ap_northeast_1_live:
          context: EcrPushLive
          filters:
            branches:
              only:
                - main
      - deploy_us_east_1_live:
          context: EcrPushLive
          filters:
            branches:
              only:
                - main
      - deploy_eu_west_1_live:
          context: EcrPushLive
          filters:
            branches:
              only:
                - main
      - deploy_ap_southeast_1_live:
          context: EcrPushLive
          filters:
            branches:
              only:
                - main
      - deploy_ap_northeast_2_live:
          context: EcrPushLive
          filters:
            branches:
              only:
                - main
      - deploy_ap_south_1_live:
          context: EcrPushLive
          filters:
            branches:
              only:
                - main
      - deploy_us_west_2_live:
          context: EcrPushLive
          filters:
            branches:
              only:
                - main
      - deploy_eu_central_1_live:
          context: EcrPushLive
          filters:
            branches:
              only:
                - main
