version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.1
  aws-ecr: circleci/aws-ecr@9.4.0

executors:
  python_default:
    docker:
      - image: cimg/python:3.7
    resource_class: medium

jobs:
  deploy_ap_northeast_1_dev:
    executor: python_default
    steps:
      - checkout
      - aws-ecr/build_and_push_image:
          account_id: "193652665524"
          region: ap-northeast-1
          repo: gs2-insight
          auth:
            - aws-cli/setup: {}
          tag: latest

  deploy_us_east_1_dev:
    executor: python_default
    steps:
      - checkout
      - aws-ecr/build_and_push_image:
          account_id: "193652665524"
          region: us-east-1
          repo: gs2-insight
          auth:
            - aws-cli/setup: {}
          tag: latest

  deploy_eu_west_1_dev:
    executor: python_default
    steps:
      - checkout
      - aws-ecr/build_and_push_image:
          account_id: "193652665524"
          region: eu-west-1
          repo: gs2-insight
          auth:
            - aws-cli/setup: {}
          tag: latest

  deploy_ap_southeast_1_dev:
    executor: python_default
    steps:
      - checkout
      - aws-ecr/build_and_push_image:
          account_id: "193652665524"
          region: ap-southeast-1
          repo: gs2-insight
          auth:
            - aws-cli/setup: {}
          tag: latest

  deploy_ap_northeast_2_dev:
    executor: python_default
    steps:
      - checkout
      - aws-ecr/build_and_push_image:
          account_id: "193652665524"
          region: ap-northeast-2
          repo: gs2-insight
          auth:
            - aws-cli/setup: {}
          tag: latest

  deploy_ap_south_1_dev:
    executor: python_default
    steps:
      - checkout
      - aws-ecr/build_and_push_image:
          account_id: "193652665524"
          region: ap-south-1
          repo: gs2-insight
          auth:
            - aws-cli/setup: {}
          tag: latest

  deploy_us_west_2_dev:
    executor: python_default
    steps:
      - checkout
      - aws-ecr/build_and_push_image:
          account_id: "193652665524"
          region: us-west-2
          repo: gs2-insight
          auth:
            - aws-cli/setup: {}
          tag: latest

  deploy_eu_central_1_dev:
    executor: python_default
    steps:
      - checkout
      - aws-ecr/build_and_push_image:
          account_id: "193652665524"
          region: eu-central-1
          repo: gs2-insight
          auth:
            - aws-cli/setup: {}
          tag: latest

  deploy_ap_northeast_1_live:
    executor: python_default
    steps:
      - checkout
      - aws-ecr/build_and_push_image:
          account_id: "258965805804"
          region: ap-northeast-1
          repo: gs2-insight
          auth:
            - aws-cli/setup: {}
          tag: latest

  deploy_us_east_1_live:
    executor: python_default
    steps:
      - checkout
      - aws-ecr/build_and_push_image:
          account_id: "258965805804"
          region: us-east-1
          repo: gs2-insight
          auth:
            - aws-cli/setup: {}
          tag: latest

  deploy_eu_west_1_live:
    executor: python_default
    steps:
      - checkout
      - aws-ecr/build_and_push_image:
          account_id: "258965805804"
          region: eu-west-1
          repo: gs2-insight
          auth:
            - aws-cli/setup: {}
          tag: latest

  deploy_ap_southeast_1_live:
    executor: python_default
    steps:
      - checkout
      - aws-ecr/build_and_push_image:
          account_id: "258965805804"
          region: ap-southeast-1
          repo: gs2-insight
          auth:
            - aws-cli/setup: {}
          tag: latest

  deploy_ap_northeast_2_live:
    executor: python_default
    steps:
      - checkout
      - aws-ecr/build_and_push_image:
          account_id: "258965805804"
          region: ap-northeast-2
          repo: gs2-insight
          auth:
            - aws-cli/setup: {}
          tag: latest

  deploy_ap_south_1_live:
    executor: python_default
    steps:
      - checkout
      - aws-ecr/build_and_push_image:
          account_id: "258965805804"
          region: ap-south-1
          repo: gs2-insight
          auth:
            - aws-cli/setup: {}
          tag: latest

  deploy_us_west_2_live:
    executor: python_default
    steps:
      - checkout
      - aws-ecr/build_and_push_image:
          account_id: "258965805804"
          region: us-west-2
          repo: gs2-insight
          auth:
            - aws-cli/setup: {}
          tag: latest

  deploy_eu_central_1_live:
    executor: python_default
    steps:
      - checkout
      - aws-ecr/build_and_push_image:
          account_id: "258965805804"
          region: eu-central-1
          repo: gs2-insight
          auth:
            - aws-cli/setup: {}
          tag: latest

workflows:
  build-and-deploy:
    jobs:
      - deploy_ap_northeast_1_dev:
          context: EcrPushDev
          filters:
            branches:
              only:
                - main
      - deploy_us_east_1_dev:
          context: EcrPushDev
          filters:
            branches:
              only:
                - main
      - deploy_eu_west_1_dev:
          context: EcrPushDev
          filters:
            branches:
              only:
                - main
      - deploy_ap_southeast_1_dev:
          context: EcrPushDev
          filters:
            branches:
              only:
                - main
      - deploy_ap_northeast_2_dev:
          context: EcrPushDev
          filters:
            branches:
              only:
                - main
      - deploy_ap_south_1_dev:
          context: EcrPushDev
          filters:
            branches:
              only:
                - main
      - deploy_us_west_2_dev:
          context: EcrPushDev
          filters:
            branches:
              only:
                - main
      - deploy_eu_central_1_dev:
          context: EcrPushDev
          filters:
            branches:
              only:
                - main

      - deploy_ap_northeast_1_live:
          context: EcrPushLive
          filters:
            branches:
              only:
                - main
      - deploy_us_east_1_live:
          context: EcrPushLive
          filters:
            branches:
              only:
                - main
      - deploy_eu_west_1_live:
          context: EcrPushLive
          filters:
            branches:
              only:
                - main
      - deploy_ap_southeast_1_live:
          context: EcrPushLive
          filters:
            branches:
              only:
                - main
      - deploy_ap_northeast_2_live:
          context: EcrPushLive
          filters:
            branches:
              only:
                - main
      - deploy_ap_south_1_live:
          context: EcrPushLive
          filters:
            branches:
              only:
                - main
      - deploy_us_west_2_live:
          context: EcrPushLive
          filters:
            branches:
              only:
                - main
      - deploy_eu_central_1_live:
          context: EcrPushLive
          filters:
            branches:
              only:
                - main
